ExclusiveMode : ExclusiveMode.sqc
	./prevodjenje ExclusiveMode vstud student abcdef
ShareMode : ShareMode.sqc
	./prevodjenje ShareMode vstud student abcdef

.PHONY: all clean

all: ExclusiveMode ShareMode
clean:
	rm -rf *.o *.bnd *.c ExclusiveMode ShareMode