dynamic_1 : dynamic_1.sqc
	./prevodjenje dynamic_1 vstud student abcdef
dynamic_2 : dynamic_2.sqc
	./prevodjenje dynamic_2 vstud student abcdef
dynamic_3 : dynamic_3.sqc
	./prevodjenje dynamic_3 vstud student abcdef
	
.PHONY: all clean
all : dynamic_1 dynamic_2 dynamic_3
clean:
	rm -rf *.c *.bnd *.o dynamic_1 dynamic_2 dynamic_3